language: java
jdk:
  oraclejdk8
cache:
  directories: $HOME/.gradle
notifications:
  email: false
script:
  ./gradlew distTar
before_deploy:
  - ls -R
deploy:
  skip_cleanup: true
  api_key:
    secure: ${GITHUB_TOKEN}
  provider: releases
  file_glob: true
  file: build/distributions/health-check-1.0-SNAPSHOT.tar
