language: java
jdk:
  oraclejdk8
cache:
  directories: $HOME/.gradle
email:
    recipients:
      - guy.peleg@tufin.com
      - stas.o@tufin.com
      - marina.bunin@tufin.com
      - shoshy.kraus@tufin.com
      - sara.movshovitz@tufin.com
      - roei.buxbaum@tufin.com
      - maayan.langer@tufin.com
      - yossi.assor@tufin.com
script:
   ./gradlew distTar
install:
    ./gradlew distTar
before_deploy:
  - export RELEASE_PKG_FILE=$(ls *.deb)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: YOUR_ENCRYPTED_API_KEY
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  on:
    tags: true
