language: java
jdk:
  oraclejdk8
cache:
  directories: $HOME/.gradle

script:
   ./gradlew distTar
   
after_script:
  - git add .
  # something@example.com
  - git config user.email "${GIT_EMAIL}"
  # First Last
  - git config user.name "${GIT_NAME}"
  - git commit -m "updating outputs"
  # https://${GH_TOKEN}@github.com/asciidoctor/asciidoctor-gradle-examples.git
  - git push -f "${GIT_URL}" gh-pages > /dev/null 2>&1
