language: java
jdk:
  oraclejdk8
cache:
  directories: $HOME/.gradle
notifications:
  email:
    recipients:
      - guy.peleg@tufin.com
      - stas.o@tufin.com
      - marina.bunin@tufin.com
      - shoshy.kraus@tufin.com
      - sara.movshovitz@tufin.com
      - roei.buxbaum@tufin.com
      - maayan.langer@tufin.com
      - yossi.assor@tufin.com 
script:
  ./gradlew distTar
before_deploy:
  - ls -R
deploy:
  skip_cleanup: true
  api_key:
    secure: $GITHUB_TOKEN
  provider: releases
  file_glob: true
  file: build/*
